### PR TITLE
breadcrumbs

### LINKED ISSUE #29: Breadcrumbs
Desktop only

Screenshot 2023-09-06 at 07 33 15

### PR DESCRIPTION
**Pull request by paolomoz**
Fix #29

Test URLs:
- Before: https://main--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia
- After: https://29-breadcrumbs--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

### CODE REVIEW

**Review by thomsebastin — APPROVED** [review]
Some files are missing EOL chars. Rest looks good.

**Comment by paolomoz** [comment]
> Some files are missing EOL chars. Rest looks good.

@thomsebastin thanks; would you be able to provide me with an example? not sure what would be expected by you on this (I am relying on eslint) Thanks!

**Comment by thomsebastin** [comment]
This is mostly an editor thing. If you add a "line break" at the end of every file this should be sorted. Manually you can do this by hitting enter when you're on the last line.

**Comment by paolomoz** [comment]
> This is mostly an editor thing. If you add a "line break" at the end of every file this should be sorted. Manually you can do this by hitting enter when you're on the last line.

ah ok that's what I was thinking of. Actually I have been following project eslint rules, where line break at the end of the file is required for .js files not for .css files
Based on eslint no other files are missing (we are skipping ffetch.js as other projects do)
If you see another file that needs to be fixed could you please share name/link? thanks!

**Pull request merged**
